apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-data-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cephfs-sc

