apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-auto-languages-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: plex-auto-languages-secrets

  data:
    - secretKey: plex_token
      remoteRef:
        key: MEDIA_SERVER__PLEX_TOKEN
