
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-qbittorrent-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-cephfs-sc
