apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rss-discord-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: rss-discord-bot

  data:
    - secretKey: token
      remoteRef:
        key: DISCORD__RSS_DISCORD_BOT_TOKEN
