apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-discord-bot-state-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs-sc
