apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-vtt-data-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: csi-cephfs-sc

