apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: foundry-vtt-scaler
  namespace: foundry-vtt
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
    resourceNames: ["foundry-vtt"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["get", "patch"]
    resourceNames: ["foundry-vtt"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
