apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hytale-scaler
  namespace: hytale
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get"]
    resourceNames: ["hytale-server"]
  - apiGroups: ["apps"]
    resources: ["statefulsets/scale"]
    verbs: ["get", "patch"]
    resourceNames: ["hytale-server"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
