apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hytale-server
spec:
  serviceName: "hytale-server"
  replicas: 1
  selector:
    matchLabels:
      app: hytale-server
  template:
    metadata:
      labels:
        app: hytale-server
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      containers:
      - name: hytale-server
        image: registry:5000/hytale-server:experimental-0.1.4-2026.01.24-6e2d4fc36
        imagePullPolicy: Always
        tty: true
        stdin: true
        ports:
        - containerPort: 5520
          protocol: UDP
        env:
        - name: TZ
          value: "America/Chicago"
        - name: SERVER_IP
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "5520"
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms4G -Xmx12G"
        - name: PROD
          value: "FALSE"
        - name: DEBUG
          value: "FALSE"
        volumeMounts:
        - mountPath: /home/container
          name: hytale-data
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
          subPath: machine-id
        resources:
          requests:
            memory: "16Gi"
            cpu: "8"
          limits:
            memory: "16Gi"
            cpu: "16"
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep -f 'java.*HytaleServer' >/dev/null 2>&1"]
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep -f 'java.*HytaleServer' >/dev/null 2>&1"]
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: seed-hytale-data
        image: registry:5000/hytale-server:experimental-0.1.4-2026.01.24-6e2d4fc36
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            SRC_BASE="/home/container"
            SRC_GAME="$SRC_BASE/game"
            DEST_BASE="/mnt/data"
            DEST_GAME="$DEST_BASE/game"
            DEST_SERVER="$DEST_GAME/Server"
            mkdir -p "$DEST_SERVER"

            if [ -f "$SRC_BASE/Assets.zip" ]; then
              cp -f "$SRC_BASE/Assets.zip" "$DEST_GAME/Assets.zip"
            elif [ -f "$SRC_GAME/Assets.zip" ]; then
              cp -f "$SRC_GAME/Assets.zip" "$DEST_GAME/Assets.zip"
            else
              echo "Missing bundled Assets.zip in image." >&2
              exit 1
            fi

            if [ -f "$SRC_BASE/HytaleServer.jar" ]; then
              cp -f "$SRC_BASE/HytaleServer.jar" "$DEST_SERVER/HytaleServer.jar"
            elif [ -f "$SRC_GAME/Server/HytaleServer.jar" ]; then
              cp -f "$SRC_GAME/Server/HytaleServer.jar" "$DEST_SERVER/HytaleServer.jar"
            elif [ -f "$SRC_GAME/HytaleServer.jar" ]; then
              cp -f "$SRC_GAME/HytaleServer.jar" "$DEST_SERVER/HytaleServer.jar"
            else
              echo "Missing bundled HytaleServer.jar in image." >&2
              exit 1
            fi

            if [ -f "$SRC_BASE/Server" ]; then
              cp -f "$SRC_BASE/Server" "$DEST_SERVER/Server"
            elif [ -f "$SRC_GAME/Server" ]; then
              cp -f "$SRC_GAME/Server" "$DEST_SERVER/Server"
            fi
        volumeMounts:
        - mountPath: /mnt/data
          name: hytale-data
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
          subPath: machine-id
      volumes:
      - name: machine-id
        configMap:
          name: hytale-machine-id
  volumeClaimTemplates:
  - metadata:
      name: hytale-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: csi-rbd-sc
