apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hytale-server
spec:
  serviceName: "hytale-server"
  replicas: 1
  selector:
    matchLabels:
      app: hytale-server
  template:
    metadata:
      labels:
        app: hytale-server
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
      containers:
      - name: hytale-server
        image: registry:5000/hytale-server:experimental-0.1.4-2026.01.24-6e2d4fc36
        imagePullPolicy: Always
        tty: true
        stdin: true
        ports:
        - containerPort: 5520
          protocol: UDP
        env:
        - name: TZ
          value: "America/Chicago"
        - name: SERVER_IP
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "5520"
        - name: PROD
          value: "FALSE"
        - name: DEBUG
          value: "FALSE"
        volumeMounts:
        - mountPath: /home/container
          name: hytale-data
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
          subPath: machine-id
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
            cpu: "4"
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep -f 'java.*HytaleServer' >/dev/null 2>&1"]
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep -f 'java.*HytaleServer' >/dev/null 2>&1"]
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      initContainers:
      - name: seed-hytale-data
        image: registry:5000/hytale-server:experimental-0.1.4-2026.01.24-6e2d4fc36
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            SRC_DIR="/home/container/game"
            DEST_DIR="/mnt/data/game"
            mkdir -p /mnt/data/game
            if [ ! -f "$SRC_DIR/Assets.zip" ] && [ -f "/home/container/Assets.zip" ]; then
              SRC_DIR="/home/container"
              DEST_DIR="/mnt/data"
            fi
            if [ ! -f "$SRC_DIR/Assets.zip" ] || { [ ! -f "$SRC_DIR/HytaleServer.jar" ] && [ ! -f "$SRC_DIR/Server" ]; }; then
              echo "Missing bundled server files in image ($SRC_DIR)." >&2
              exit 1
            fi
            mkdir -p "$DEST_DIR"
            cp -f "$SRC_DIR/Assets.zip" "$DEST_DIR/"
            if [ -f "$SRC_DIR/HytaleServer.jar" ]; then
              cp -f "$SRC_DIR/HytaleServer.jar" "$DEST_DIR/"
            fi
            if [ -f "$SRC_DIR/Server" ]; then
              cp -f "$SRC_DIR/Server" "$DEST_DIR/"
            fi
        volumeMounts:
        - mountPath: /mnt/data
          name: hytale-data
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
          subPath: machine-id
      volumes:
      - name: machine-id
        configMap:
          name: hytale-machine-id
  volumeClaimTemplates:
  - metadata:
      name: hytale-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: csi-rbd-sc
