apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hytale-discord-bot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: hytale-discord-bot

  data:
    - secretKey: token
      remoteRef:
        key: HYTALE__DISCORD_BOT_TOKEN
