apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical

  target:
    name: filebrowser-secrets

  data:
    - secretKey: password
      remoteRef:
        key: FOUNDRY_VTT__FILEBROWSER_PASSWORD


