apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: filebrowser
spec:
  serviceName: "filebrowser"
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        fsGroup: 1000
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 300

      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: filebrowser-data
              mountPath: /data

      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            - name: FB_DATABASE
              value: /data/database.db
            - name: FB_NOAUTH
              value: "true"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /srv
              name: foundry-vtt-data
              readOnly: false
            - mountPath: /data
              name: filebrowser-data

      volumes:
        - name: foundry-vtt-data
          persistentVolumeClaim:
            claimName: foundry-vtt-data

  volumeClaimTemplates:
    - metadata:
        name: filebrowser-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: csi-cephfs-sc
