apiVersion: batch/v1
kind: Job
metadata:
  name: plex-backup-job
spec:
  template:
    spec:
      serviceAccountName: plex-backup-sa
      containers:
        - name: backup
          image: bitnami/kubectl:1.32-debian-12
          securityContext:
            runAsUser: 0
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              
              cleanup() {
                echo "Ensuring Plex is scaled back up...";
                kubectl scale statefulset plex --replicas=1 -n media-server || echo "Failed to scale up Plex"
              }

              trap cleanup EXIT

              echo "Installing rsync...";
              apt update && apt install -y rsync

              echo "Scaling down Plex...";
              kubectl scale statefulset plex --replicas=0 -n media-server

              echo "Waiting for Plex to terminate...";
              while kubectl get pods -l app=plex -n media-server | grep -q Running; do sleep 1; done

              echo "Backing up volume...";
              mkdir -p /backup/media-server/plex/
              rsync -avh /source/ /backup/media-server/plex/ || \
                (code=$?; if [ "$code" -eq 24 ]; then echo "Warning: some files vanished during transfer. Continuing..."; else exit $code; fi)
          volumeMounts:
            - name: source
              mountPath: /source
            - name: destination
              mountPath: /backup
      restartPolicy: Never
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: plex-data-plex-0
        - name: destination
          persistentVolumeClaim:
            claimName: plex-backup-pvc
