apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: csi-cephfs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 20Gi
